[build]
  command = "npm install --production=false && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express"]

[build.environment]
  NODE_VERSION = "18"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 5173
  port = 8888
  publish = "dist"
