[build]
  base = "/"
  publish = "dist"
  command = "npm install && npm run build"
  environment = { NODE_VERSION = "18" }

[build.environment]
  VITE_API_URL = "/.netlify/functions"

[functions]
  directory = "backend/netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
