[build]
  command = "CI=false npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "/api"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
