[build]
  command = "npm ci --ignore-scripts && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_API_URL = "/.netlify/functions"
  NODE_ENV = "production"
  PYTHON_VERSION = "3.11"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
