[build]
  command = "npm ci && npm run build"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./package-lock.json"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "/.netlify/functions"
  NODE_ENV = "production"
  CI = "true"
  PATH = "./node_modules/.bin:$PATH"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
