[build]
  command = "chmod +x build.sh && ./build.sh"
  publish = "dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./package-lock.json"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "/api"
  CI = "false"
  NPM_FLAGS = "--legacy-peer-deps --no-audit --no-fund"
  PATH = "./node_modules/.bin:$PATH"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
